### PR TITLE
made the translations file

### PR DESCRIPTION
**Pull request by AjinkyaBorate**
created the "translations" folder and added "es.json" to it.
Performed the translation on your given topic.

### CODE REVIEW

**Comment by AjinkyaBorate** [comment]
I have sent the PR.
please evaluate and respond.

**Comment by charandeepsinghb** [comment]
Fixes #11

**Comment by charandeepsinghb** [comment]
@AjinkyaBorate Add a comment in the task #11 so that I can assign it to you and close the task after merging this PR

**Comment by AjinkyaBorate** [comment]
What to add

**Comment by charandeepsinghb** [comment]
Add any comment in the issue #11.
That way I will be able to assign the task to you.

**Comment by AjinkyaBorate** [comment]
Ok

**Review by charandeepsinghb — APPROVED** [review]

**Pull request merged**
